version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Baku"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Baku"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Baku"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Baku"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Baku"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "deps"
      include: "scope"
